### ISSUE TITLE
Use MAX32625PICO to bootloader program MAX78000

### ISSUE THREAD

**Issue by chaitanya-smartrotamac** [analogdevicesinc/max78000-secure-loader#4]
Purchased MAX32625PICO as PICO 2 is not available or removed. Documentation is not at all clear on how to use MAX32625PICO to bootload the program.  
Can some one help me?

**Comment by Jake-Carter** [comment]
Hi @chaitanya-smartrotamac, I've been reviewing our documentation.  I agree that it is not clear at all.  I'm tracking down some resources to support you.  Theoretically we can port the [Bootloader_Host](https://github.com/Analog-Devices-MSDK/msdk/tree/main/Examples/MAX32660/Bootloader_Host) example to the MAX78000, but I am confirming internally exactly which version of the bootloader is on the MAX78000.  There are some mismatches in our documentation about that as well.

Apologies for the confusion, I will keep you updated as I uncover some more info.

**Comment by maximreza** [comment]
Hi
I am looking at this issue as well as issue (#3)

If you have a MAX32630FTHR, you can setup a programming jig through I2C.

The document directory is here:
https://github.com/MaximIntegratedAI/secure-loader/tree/main/MAX78000_MSBL/Docs

You need to breadboard MAX32630FTHR per this [document](https://github.com/MaximIntegratedAI/secure-loader/blob/main/MAX78000_MSBL/Docs/MAX78000_Secure_Bootloader_InApplication_Programming.pdf). This will allow you to have a secure boot mechanism in place as well. Tools are written in Python and are [here](https://github.com/MaximIntegratedAI/secure-loader/tree/main/MAX78000_MSBL).

The other option is the UART bootloader explained in the [MAX78000 user's guide](https://www.analog.com/media/en/technical-documentation/user-guides/max78000-user-guide.pdf). Look under 26.4 to how to enter bootloader and 26.8 for general commands.

Hope this helps.

**Comment by chaitanya-smartrotamac** [comment]
Thank you @maximreza for your response.

Problem is with the availability. 
I have a MAX32625PICO and 2 MAX78000 boards available with me to test the secure-loader setup which is not possible.
MAX32630FTHR related only bin file is available. If the source is available I could port to MAX78000 to act as host and test.
My actual MAX78000 device has some other controller as HOST which I need to develop.

So If the Bootloader host program for MAX32630 source files are available those will be very helpful.

My next question :

Can we bootload the code using the MAX32625PICO alone using serial(UART/I2C/SPI)? as it is mentioned as it can be used as a serial bridge.

**Comment by maximreza** [comment]
Hi 
sorry for delayed response. I will check if the MAX32630 source code is available. In the mean time if you do not care about the secure boot, you may want to look at the ROM bootloader protocol available on MAX78000 and documented in the [MAX78000 User's guide](https://www.analog.com/media/en/technical-documentation/user-guides/max78000-user-guide.pdf).
Look at page 365?
